// The languages Meta accepts for a WhatsApp template, labelled in the language
// itself where that helps someone find their own. Spanish and English variants
// come first because that is what most businesses here pick.
export const TEMPLATE_LANGUAGES: Record<string, string> = {
  es: "Español",
  es_CO: "Español (Colombia)",
  es_MX: "Español (México)",
  es_AR: "Español (Argentina)",
  es_CL: "Español (Chile)",
  es_CR: "Español (Costa Rica)",
  es_DO: "Español (República Dominicana)",
  es_EC: "Español (Ecuador)",
  es_HN: "Español (Honduras)",
  es_PA: "Español (Panamá)",
  es_PE: "Español (Perú)",
  es_ES: "Español (España)",
  es_UY: "Español (Uruguay)",
  en: "English",
  en_US: "English (US)",
  en_GB: "English (UK)",
  en_AE: "English (UAE)",
  en_AU: "English (Australia)",
  en_CA: "English (Canada)",
  en_GH: "English (Ghana)",
  en_IE: "English (Ireland)",
  en_IN: "English (India)",
  en_JM: "English (Jamaica)",
  en_MY: "English (Malaysia)",
  en_NZ: "English (New Zealand)",
  en_QA: "English (Qatar)",
  en_SG: "English (Singapore)",
  en_UG: "English (Uganda)",
  en_ZA: "English (South Africa)",
  pt_BR: "Português (Brasil)",
  pt_PT: "Português (Portugal)",
  fr: "Français",
  fr_BE: "Français (Belgique)",
  fr_CA: "Français (Canada)",
  fr_CH: "Français (Suisse)",
  fr_CI: "Français (Côte d'Ivoire)",
  fr_MA: "Français (Maroc)",
  de: "Deutsch",
  de_AT: "Deutsch (Österreich)",
  de_CH: "Deutsch (Schweiz)",
  it: "Italiano",
  nl: "Nederlands",
  nl_BE: "Nederlands (België)",
  ca: "Català",
  af: "Afrikaans",
  sq: "Shqip",
  ar: "العربية",
  ar_EG: "العربية (مصر)",
  ar_AE: "العربية (الإمارات)",
  ar_LB: "العربية (لبنان)",
  ar_MA: "العربية (المغرب)",
  ar_QA: "العربية (قطر)",
  az: "Azərbaycan",
  be_BY: "Беларуская",
  bn: "বাংলা",
  bn_IN: "বাংলা (ভারত)",
  bg: "Български",
  zh_CN: "中文 (简体)",
  zh_HK: "中文 (香港)",
  zh_TW: "中文 (繁體)",
  hr: "Hrvatski",
  cs: "Čeština",
  da: "Dansk",
  prs_AF: "دری",
  et: "Eesti",
  fil: "Filipino",
  fi: "Suomi",
  ka: "ქართული",
  el: "Ελληνικά",
  gu: "ગુજરાતી",
  ha: "Hausa",
  he: "עברית",
  hi: "हिन्दी",
  hu: "Magyar",
  id: "Bahasa Indonesia",
  ga: "Gaeilge",
  ja: "日本語",
  kn: "ಕನ್ನಡ",
  kk: "Қазақ",
  rw_RW: "Kinyarwanda",
  ko: "한국어",
  ky_KG: "Кыргызча",
  lo: "ລາວ",
  lv: "Latviešu",
  lt: "Lietuvių",
  mk: "Македонски",
  ms: "Bahasa Melayu",
  ml: "മലയാളം",
  mr: "मराठी",
  nb: "Norsk",
  ps_AF: "پښتو",
  fa: "فارسی",
  pl: "Polski",
  pa: "ਪੰਜਾਬੀ",
  ro: "Română",
  ru: "Русский",
  sr: "Српски",
  si_LK: "සිංහල",
  sk: "Slovenčina",
  sl: "Slovenščina",
  sw: "Kiswahili",
  sv: "Svenska",
  ta: "தமிழ்",
  te: "తెలుగు",
  th: "ไทย",
  tr: "Türkçe",
  uk: "Українська",
  ur: "اردو",
  uz: "Oʻzbek",
  vi: "Tiếng Việt",
  zu: "isiZulu",
};

export const TEMPLATE_LANGUAGE_CODES = Object.keys(TEMPLATE_LANGUAGES);

export function templateLanguageLabel(code: string): string {
  return TEMPLATE_LANGUAGES[code] ? `${TEMPLATE_LANGUAGES[code]} · ${code}` : code;
}
